#!/usr/bin/env -S python3 -u

import argparse
import socket
import json
import select
import sys
import hashlib


def checksum(data):
    return hashlib.md5(data.encode()).hexdigest()


class Receiver:
    def __init__(self):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(("0.0.0.0", 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)

        self.remote_host = None
        self.remote_port = None

    def send(self, message):
        self.log("Sent message %s" % json.dumps(message))
        self.socket.sendto(
            json.dumps(message).encode("utf-8"),
            (self.remote_host, self.remote_port)
        )

    def recv(self, sock):
        data, addr = sock.recvfrom(65535)

        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        if addr != (self.remote_host, self.remote_port):
            self.log("Error: Received response from unexpected remote; ignoring")
            return None

        try:
            msg = json.loads(data.decode("utf-8"))
        except Exception:
            self.log("Corrupted JSON -> dropping")
            return None

        self.log("Received message %s" % msg)
        return msg

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def run(self):
        sequence = 0          # next expected byte
        buffer = {}           # seq -> payload

        while True:
            socks = select.select([self.socket], [], [])[0]

            for conn in socks:
                msg = self.recv(conn)

                if not isinstance(msg, dict):
                    continue

                if msg.get("type") != "msg":
                    continue

                if "seq" not in msg or "data" not in msg or "checksum" not in msg:
                    self.log("Malformed packet -> dropping")
                    continue

                seq = msg["seq"]
                data = msg["data"]
                pkt_checksum = msg["checksum"]

                if not isinstance(seq, int) or not isinstance(data, str) or not isinstance(pkt_checksum, str):
                    self.log("Malformed packet -> dropping")
                    continue

                if checksum(data) != pkt_checksum:
                    self.log("Corrupted packet -> dropping")
                    continue

                if seq < sequence:
                    self.send({
                        "type": "ack",
                        "seq": sequence,
                        "checksum": checksum(str(sequence))
                    })
                    continue

                if seq not in buffer:
                    buffer[seq] = data

                while sequence in buffer:
                    payload = buffer.pop(sequence)
                    print(payload, end="", flush=True)
                    sequence += len(payload)

                self.send({
                    "type": "ack",
                    "seq": sequence,
                    "checksum": checksum(str(sequence))
                })


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="receive data")
    parser.parse_args()

    receiver = Receiver()
    receiver.run()
